/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 extraSpaceShipTemp.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/extraSpaceShipTemp.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ExtraSpaceship" geometry={nodes.ExtraSpaceship.geometry} material={nodes.ExtraSpaceship.material} position={[973.193, 0, -146.444]} scale={[21.731, 4.626, 13.163]} />
      </group>
    </group>
  )
}

useGLTF.preload('/extraSpaceShipTemp.glb')
