/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/cockpit.glb 
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function CommandCenter(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/cockpit.glb");

  // Refs for video elements
  const screenVideoRef = useRef(null);
  const mainScreenVideoRef = useRef(null);
  const secondaryScreenVideoRef = useRef(null);

  // Refs for video textures
  const screenTextureRef = useRef(null);
  const mainScreenTextureRef = useRef(null);
  const secondaryScreenTextureRef = useRef(null);

  // State to track when videos are ready
  const [videosReady, setVideosReady] = useState(false);

  // Load fallback static textures (will be replaced by videos when ready)
  const fallbackScreenTexture = useTexture("textures/command_center_screen.jpg");
  const fallbackMainScreen = useTexture("textures/command_center_mainScreen.jpg");
  const fallbackSecondaryScreen = useTexture(
    "textures/command_center_secondaryScreen.png"
  );

  // Set fallback texture properties
  fallbackScreenTexture.flipY = false;
  fallbackScreenTexture.encoding = THREE.sRGBEncoding;
  fallbackMainScreen.flipY = false;
  fallbackMainScreen.encoding = THREE.sRGBEncoding;
  fallbackSecondaryScreen.flipY = false;
  fallbackSecondaryScreen.encoding = THREE.sRGBEncoding;

  // Initialize video textures
  useEffect(() => {
    let videosLoaded = 0;
    const totalVideos = 3;
    let isMounted = true;

    // Helper function to safely play video
    const playVideo = async (video, name) => {
      try {
        // Only play if video is paused and ready
        if (video.paused && video.readyState >= 2) {
          await video.play();
        }
      } catch (error) {
        // Ignore AbortError - it's harmless (video was paused before play completed)
        if (error.name !== "AbortError" && error.name !== "NotAllowedError") {
          console.warn(`Failed to play ${name} video:`, error);
        }
      }
    };

    const checkAllVideosReady = () => {
      if (!isMounted) return;
      videosLoaded++;
      if (videosLoaded === totalVideos) {
        setVideosReady(true);
      }
    };

    // Screen video
    const screenVideo = document.createElement("video");
    screenVideo.src = "./textures/screen/screen_animation.mp4";
    screenVideo.loop = true;
    screenVideo.muted = true;
    screenVideo.playsInline = true;
    screenVideo.crossOrigin = "anonymous";
    screenVideo.preload = "auto";
    screenVideoRef.current = screenVideo;

    const handleScreenReady = () => {
      checkAllVideosReady();
      // Play video when ready
      if (isMounted) {
        playVideo(screenVideo, "screen");
      }
    };

    const handleScreenLoaded = () => {
      // Try to play when data is loaded
      if (isMounted && screenVideo.paused) {
        playVideo(screenVideo, "screen");
      }
    };

    const handleScreenError = (error) => {
      console.warn("Failed to load screen video:", error);
      checkAllVideosReady(); // Continue even if video fails
    };

    screenVideo.addEventListener("canplaythrough", handleScreenReady);
    screenVideo.addEventListener("loadeddata", handleScreenLoaded);
    screenVideo.addEventListener("error", handleScreenError);

    // Main screen video
    const mainScreenVideo = document.createElement("video");
    mainScreenVideo.src = "./textures/mainScreen/mainScreen_animation.mp4";
    mainScreenVideo.loop = true;
    mainScreenVideo.muted = true;
    mainScreenVideo.playsInline = true;
    mainScreenVideo.crossOrigin = "anonymous";
    mainScreenVideo.preload = "auto";
    mainScreenVideoRef.current = mainScreenVideo;

    const handleMainScreenReady = () => {
      checkAllVideosReady();
      // Play video when ready
      if (isMounted) {
        playVideo(mainScreenVideo, "mainScreen");
      }
    };

    const handleMainScreenLoaded = () => {
      // Try to play when data is loaded
      if (isMounted && mainScreenVideo.paused) {
        playVideo(mainScreenVideo, "mainScreen");
      }
    };

    const handleMainScreenError = (error) => {
      console.warn("Failed to load mainScreen video:", error);
      checkAllVideosReady(); // Continue even if video fails
    };

    mainScreenVideo.addEventListener("canplaythrough", handleMainScreenReady);
    mainScreenVideo.addEventListener("loadeddata", handleMainScreenLoaded);
    mainScreenVideo.addEventListener("error", handleMainScreenError);

    // Secondary screen video
    const secondaryScreenVideo = document.createElement("video");
    secondaryScreenVideo.src =
      "./textures/secondaryScreen/secondaryScreen_animation.mp4";
    secondaryScreenVideo.loop = true;
    secondaryScreenVideo.muted = true;
    secondaryScreenVideo.playsInline = true;
    secondaryScreenVideo.crossOrigin = "anonymous";
    secondaryScreenVideo.preload = "auto";
    secondaryScreenVideoRef.current = secondaryScreenVideo;

    const handleSecondaryScreenReady = () => {
      checkAllVideosReady();
      // Play video when ready
      if (isMounted) {
        playVideo(secondaryScreenVideo, "secondaryScreen");
      }
    };

    const handleSecondaryScreenLoaded = () => {
      // Try to play when data is loaded
      if (isMounted && secondaryScreenVideo.paused) {
        playVideo(secondaryScreenVideo, "secondaryScreen");
      }
    };

    const handleSecondaryScreenError = (error) => {
      console.warn("Failed to load secondaryScreen video:", error);
      checkAllVideosReady(); // Continue even if video fails
    };

    secondaryScreenVideo.addEventListener(
      "canplaythrough",
      handleSecondaryScreenReady
    );
    secondaryScreenVideo.addEventListener("loadeddata", handleSecondaryScreenLoaded);
    secondaryScreenVideo.addEventListener("error", handleSecondaryScreenError);

    // Create video textures
    try {
      screenTextureRef.current = new THREE.VideoTexture(screenVideo);
      screenTextureRef.current.flipY = false;
      screenTextureRef.current.encoding = THREE.sRGBEncoding;
      screenTextureRef.current.minFilter = THREE.LinearFilter;
      screenTextureRef.current.magFilter = THREE.LinearFilter;
    } catch (error) {
      console.warn("Failed to create screen video texture:", error);
    }

    try {
      mainScreenTextureRef.current = new THREE.VideoTexture(mainScreenVideo);
      mainScreenTextureRef.current.flipY = false;
      mainScreenTextureRef.current.encoding = THREE.sRGBEncoding;
      mainScreenTextureRef.current.minFilter = THREE.LinearFilter;
      mainScreenTextureRef.current.magFilter = THREE.LinearFilter;
    } catch (error) {
      console.warn("Failed to create mainScreen video texture:", error);
    }

    try {
      secondaryScreenTextureRef.current = new THREE.VideoTexture(
        secondaryScreenVideo
      );
      secondaryScreenTextureRef.current.flipY = false;
      secondaryScreenTextureRef.current.encoding = THREE.sRGBEncoding;
      secondaryScreenTextureRef.current.minFilter = THREE.LinearFilter;
      secondaryScreenTextureRef.current.magFilter = THREE.LinearFilter;
    } catch (error) {
      console.warn("Failed to create secondaryScreen video texture:", error);
    }

    // Cleanup function
    return () => {
      isMounted = false;

      screenVideo.removeEventListener("canplaythrough", handleScreenReady);
      screenVideo.removeEventListener("loadeddata", handleScreenLoaded);
      screenVideo.removeEventListener("error", handleScreenError);
      mainScreenVideo.removeEventListener(
        "canplaythrough",
        handleMainScreenReady
      );
      mainScreenVideo.removeEventListener("loadeddata", handleMainScreenLoaded);
      mainScreenVideo.removeEventListener("error", handleMainScreenError);
      secondaryScreenVideo.removeEventListener(
        "canplaythrough",
        handleSecondaryScreenReady
      );
      secondaryScreenVideo.removeEventListener(
        "loadeddata",
        handleSecondaryScreenLoaded
      );
      secondaryScreenVideo.removeEventListener("error", handleSecondaryScreenError);

      // Pause videos before cleaning up
      if (screenVideo) {
        screenVideo.pause();
        screenVideo.src = "";
      }
      if (mainScreenVideo) {
        mainScreenVideo.pause();
        mainScreenVideo.src = "";
      }
      if (secondaryScreenVideo) {
        secondaryScreenVideo.pause();
        secondaryScreenVideo.src = "";
      }

      screenTextureRef.current?.dispose();
      mainScreenTextureRef.current?.dispose();
      secondaryScreenTextureRef.current?.dispose();
    };
  }, []);

  // Create materials with fallback textures initially
  const screenMaterial = useRef(
    new THREE.MeshStandardMaterial({
      map: fallbackScreenTexture,
    })
  ).current;

  const mainScreenMaterial = useRef(
    new THREE.MeshStandardMaterial({
      map: fallbackMainScreen,
    })
  ).current;

  const secondaryScreenMaterial = useRef(
    new THREE.MeshStandardMaterial({
      map: fallbackSecondaryScreen,
    })
  ).current;

  // Update materials when video textures are ready
  useEffect(() => {
    if (videosReady) {
      if (screenTextureRef.current) {
        screenMaterial.map = screenTextureRef.current;
        screenMaterial.needsUpdate = true;
      }
      if (mainScreenTextureRef.current) {
        mainScreenMaterial.map = mainScreenTextureRef.current;
        mainScreenMaterial.needsUpdate = true;
      }
      if (secondaryScreenTextureRef.current) {
        secondaryScreenMaterial.map = secondaryScreenTextureRef.current;
        secondaryScreenMaterial.needsUpdate = true;
      }
    }
  }, [videosReady, screenMaterial, mainScreenMaterial, secondaryScreenMaterial]);

  // Update video textures every frame
  useFrame(() => {
    if (screenTextureRef.current && videosReady) {
      screenTextureRef.current.needsUpdate = true;
    }
    if (mainScreenTextureRef.current && videosReady) {
      mainScreenTextureRef.current.needsUpdate = true;
    }
    if (secondaryScreenTextureRef.current && videosReady) {
      secondaryScreenTextureRef.current.needsUpdate = true;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh056.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.Mesh056_1.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh056_2.geometry} material={screenMaterial} />
      <mesh
        geometry={nodes.Mesh056_3.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh056_4.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh056_5.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh056_6.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh056_7.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh056_8.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh056_9.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh056_10.geometry}
        material={mainScreenMaterial}
      />
      <mesh
        geometry={nodes.Mesh056_11.geometry}
        material={secondaryScreenMaterial}
      />
    </group>
  );
}

useGLTF.preload("./models/spaceship/cockpit.glb");
