/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/cockpit.glb 
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";

export function CommandCenter(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/cockpit.glb");

  const screenTexture = useTexture("textures/command_center_screen.jpg");
  const mainScreen = useTexture("textures/command_center_mainScreen.jpg");
  const secondaryScreen = useTexture(
    "textures/command_center_secondaryScreen.png"
  );

  const screenMaterial = new THREE.MeshStandardMaterial({
    map: screenTexture,
  });
  const mainScreenMaterial = new THREE.MeshStandardMaterial({
    map: mainScreen,
  });
  const secondaryScreenMaterial = new THREE.MeshStandardMaterial({
    map: secondaryScreen,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh056.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.Mesh056_1.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh056_2.geometry} material={screenMaterial} />
      <mesh
        geometry={nodes.Mesh056_3.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh056_4.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh056_5.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh056_6.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh056_7.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh056_8.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh056_9.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh056_10.geometry}
        material={mainScreenMaterial}
      />
      <mesh
        geometry={nodes.Mesh056_11.geometry}
        material={secondaryScreenMaterial}
      />
    </group>
  );
}

useGLTF.preload("./models/spaceship/cockpit.glb");
