/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Earth.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Earth(props) {
  const { nodes } = useGLTF("./models/spaceship/Earth.glb");
  const groupRef = useRef();

  const earthTexture = useTexture("textures/earthTexture.jpg");
  earthTexture.flipY = false;
  earthTexture.encoding = THREE.sRGBEncoding;

  const earthMaterial = new THREE.MeshStandardMaterial({ map: earthTexture });

  useFrame((_, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.0;
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Earth.geometry} material={earthMaterial} />
    </group>
  );
}

useGLTF.preload('./models/spaceship/Earth.glb')
