/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Earth.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Earth(props) {
  const { nodes, materials } = useGLTF('./models/spaceship/Earth.glb')
  
  // Load earth texture following the same pattern as House_Interior.jsx
  const earthTexture = useTexture('textures/earthTexture.jpg')
  earthTexture.flipY = false
  earthTexture.encoding = THREE.sRGBEncoding
  
  const earthMaterial = new THREE.MeshStandardMaterial({
    map: earthTexture,
  })
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Earth.geometry} material={earthMaterial} />
    </group>
  )
}

useGLTF.preload('./models/spaceship/Earth.glb')
