/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 EarthAtmosphere.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function EarthAtmosphere(props) {
  const { nodes, materials } = useGLTF('./models/spaceship/EarthAtmosphere.glb')
  const groupRef = useRef()
  
  // Load atmosphere texture with alpha/transparency
  const atmosphereTexture = useTexture('textures/EarthAtmosphere.png')
  atmosphereTexture.flipY = false
  atmosphereTexture.encoding = THREE.sRGBEncoding
  
  // Create transparent material for atmosphere
  const atmosphereMaterial = new THREE.MeshStandardMaterial({
    map: atmosphereTexture,
    transparent: true,
    opacity: 0.8, // Adjust opacity as needed (0 = fully transparent, 1 = opaque)
    alphaMap: atmosphereTexture, // Use the texture's alpha channel if it has one
    side: THREE.DoubleSide, // Render both sides for atmosphere
  })
  
  // Rotate atmosphere around Y-axis (vertical axis) to match Earth's rotation
  useFrame((_, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.01 // Same rotation speed as Earth
    }
  })
  
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.EarthAtmosphere.geometry} material={atmosphereMaterial} />
    </group>
  )
}

useGLTF.preload('./models/spaceship/EarthAtmosphere.glb')
