/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 extraSpaceShipTemp.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function ExtraSpaceShipTemp(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/spaceship/extraSpaceShipTemp.glb')
  const { actions, mixer } = useAnimations(animations, group)
  const scroll = useScroll()

  // Use only the first animation
  const clip = animations[0]

  useEffect(() => {
    if (clip && actions[clip.name]) {
      const action = actions[clip.name]
      action.enabled = true
      action.play()
      // pause the animation so we can control manually
      action.paused = true
      action.setEffectiveTimeScale(1)
      action.setEffectiveWeight(1)
    } else {
      console.warn('ExtraSpaceShipTemp: No animation clip or action found', { 
        animationsCount: animations.length, 
        clipName: clip?.name,
        availableActions: Object.keys(actions)
      })
    }
  }, [actions, clip])

  // Animate based on scroll
  useFrame(() => {
    if (clip && mixer && actions[clip.name]) {
      const scrollOffset = scroll.offset // 0 → 1
      // set the animation time based on scroll
      actions[clip.name].time = clip.duration * scrollOffset
      mixer.update(0) // required to apply the time
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ExtraSpaceship" geometry={nodes.ExtraSpaceship.geometry} material={nodes.ExtraSpaceship.material} position={[973.193, 0, -146.444]} scale={[21.731, 4.626, 13.163]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/spaceship/extraSpaceShipTemp.glb')
