/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/MedicalBox.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import { useRef, useState } from "react";
import { useProductStore } from "../store/useProductsStore";

export function MedicalBox(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/MedicalBox.glb");
  const ref = useRef();
  const [hovered, setHover] = useState(null);
  const setActiveProduct = useProductStore((s) => s.setActiveProduct);
  const setProductHovered = useProductStore((s) => s.setProductHovered);

  const productInfo = {
    title: "Medical Trolley",
    description:
      "The Medical Trolley is a sturdy, wheeled cart designed for nurses to safely store and administer medications to hospitalized patients. With multiple compartments and secure drawers, it keeps medicines organized and easily accessible, ensuring efficient and safe patient care. Its smooth-rolling wheels allow effortless mobility throughout the hospital or ward.",
    priceNow: "$199",
    category: "Medical Equipments",
    image: "./images/medical-trolley.jpg",
  };

  return (
    <Select enabled={hovered}>
      <group
        {...props}
        ref={ref}
        onPointerOver={() => {
          setHover(true);
          setActiveProduct(productInfo);
          setProductHovered(true);
        }}
        onPointerOut={() => {
          setHover(false);
          setProductHovered(false);
        }}
      >
        <mesh
          geometry={nodes.Armature_low_1.geometry}
          material={materials["lambert1.002"]}
        />
        <mesh
          geometry={nodes.Armature_low_2.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Armature_low_3.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </Select>
  );
}

useGLTF.preload("./models/spaceship/MedicalBox.glb");
