/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/Monitor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import { useRef, useState } from "react";
import { useProductStore } from "../store/useProductsStore";

export function MedicalMonitor(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/Monitor.glb");
  const ref = useRef();
  const [hovered, setHover] = useState(null);
  const setActiveProduct = useProductStore((s) => s.setActiveProduct);
  const setProductHovered = useProductStore((s) => s.setProductHovered);

  const productInfo = {
    title: "Medical Vital Signs Monitor",
    description:
      "The Medical Vital Signs Monitor is a compact, reliable device that tracks heart rate, blood pressure, oxygen saturation, and temperature, providing real-time data for efficient patient monitoring.",
    priceWas: "$299",
    priceNow: "$199",
    category: "Medical Equipments",
    image: "./images/vital-monitor.jpg",
  };

  return (
    <Select enabled={hovered}>
      <group
        {...props}
        ref={ref}
        onPointerOver={() => {
          setHover(true);
          setActiveProduct(productInfo);
          setProductHovered(true);
        }}
        onPointerOut={() => {
          setHover(false);
          setProductHovered(false);
        }}
      >
        <mesh
          geometry={nodes.monitor_1.geometry}
          material={materials.monitor}
        />
        <mesh
          geometry={nodes.monitor_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </Select>
  );
}

useGLTF.preload("./models/spaceship/Monitor.glb");
