/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/door_1_with_animation.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function SpaceshipDoor1(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/spaceship/door_1_with_animation.glb"
  );
  const { actions, mixer } = useAnimations(animations, group);
  const scroll = useScroll();

  // Use only the first animation
  const clip = animations[0];

  useEffect(() => {
    if (clip) {
      actions[clip.name]?.play();
      // pause the animation so we can control manually
      actions[clip.name].paused = true;
    }
  }, [actions, clip]);

  // Animate based on scroll
  useFrame(() => {
    if (clip && mixer) {
      const scrollOffset = scroll.offset; // 0 → 1
      // set the animation time based on scroll
      actions[clip.name].time = clip.duration * scrollOffset * 4.35;
      mixer.update(0); // required to apply the time
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="door_itself">
          <mesh
            name="Mesh036"
            geometry={nodes.Mesh036.geometry}
            material={materials.Glass_normal}
          />
          <mesh
            name="Mesh036_1"
            geometry={nodes.Mesh036_1.geometry}
            material={materials.Wood}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/spaceship/door_1_with_animation.glb");
