/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/model.glb 
*/

import { useGLTF } from "@react-three/drei";

export function Spaceship(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Ammo_silos.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.antenae.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.back_floor.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.bath_room_carpet1.geometry}
        material={materials.Carpet}
      />
      <mesh
        geometry={nodes.cargo_lift.geometry}
        material={materials.Cargo_lift}
      />
      <mesh
        geometry={nodes.engine_plates.geometry}
        material={materials.Engine_plates}
      />
      <mesh
        geometry={nodes.entry_walls_low.geometry}
        material={materials.Entry_walls}
      />
      <mesh
        geometry={nodes.exterior_back_leg_L1.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.exterior_back_leg_R1.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.front_circle_glass.geometry}
        material={materials.Glass_normal}
      />
      <mesh
        geometry={nodes.front_feet.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Happy_digital_face.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Line001.geometry} material={materials.White_Mat} />
      <mesh
        geometry={nodes.pCube1149.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.pCube117.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh geometry={nodes.pCube1183.geometry} material={materials.Steel} />
      <mesh geometry={nodes.pCube891.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.pCube895.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.pCylinder221.geometry}
        material={materials.Light_Orange}
      />
      <group position={[-0.791, 0, 0]}>
        <mesh
          geometry={nodes.Mesh112.geometry}
          material={materials.Light_Orange}
        />
        <mesh
          geometry={nodes.Mesh112_1.geometry}
          material={materials.Orange_paint_metal}
        />
        <mesh
          geometry={nodes.Mesh112_2.geometry}
          material={materials.Light_Fire}
        />
        <mesh
          geometry={nodes.Mesh112_3.geometry}
          material={materials.Entry_pipe}
        />
      </group>
      <group position={[2.021, -2.188, 3.225]} scale={0.415}>
        <mesh
          geometry={nodes.Mesh114.geometry}
          material={materials.Light_Orange}
        />
        <mesh
          geometry={nodes.Mesh114_1.geometry}
          material={materials.Orange_paint_metal}
        />
        <mesh
          geometry={nodes.Mesh114_2.geometry}
          material={materials.Light_Fire}
        />
        <mesh
          geometry={nodes.Mesh114_3.geometry}
          material={materials.Entry_pipe}
        />
      </group>
      <mesh
        geometry={nodes.polySurface3355.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.polySurface3456.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.polySurface3719.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.polySurface3765.geometry}
        material={materials.Steel}
      />
      <mesh
        geometry={nodes.restroom_bin.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Sink_top_large_light.geometry}
        material={materials.Wood}
      />
      <mesh geometry={nodes.sweep92.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.sweep93.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.sweep94.geometry} material={materials.lambert1} />
      <mesh
        geometry={nodes.tunnel_to_cockpit.geometry}
        material={materials.Steel}
      />
      <mesh geometry={nodes.utils_signs.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.wooden_decor_bedroom.geometry}
        material={materials.Rosewood}
      />
      <mesh
        geometry={nodes.wooden_floor.geometry}
        material={materials.Rosewood_floor}
      />
      <mesh
        geometry={nodes.wooden_transition_planks.geometry}
        material={materials.Rosewood}
      />
      <mesh
        geometry={nodes.Mesh086.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh086_1.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh086_2.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh086_3.geometry}
        material={materials.Painted_wood}
      />
      <mesh
        geometry={nodes.Mesh086_4.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh086_5.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh086_6.geometry}
        material={materials.Glass_normal}
      />
      <mesh geometry={nodes.Mesh086_7.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh086_8.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Mesh086_9.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh086_10.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh086_11.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh086_12.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh086_13.geometry} material={materials.Wood} />
      <mesh
        geometry={nodes.Mesh086_14.geometry}
        material={materials.Orange_basic}
      />
      <mesh geometry={nodes.Mesh086_15.geometry} material={materials.Soil} />
      <mesh
        geometry={nodes.Mesh086_16.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.Mesh086_17.geometry}
        material={materials.Polished_metal}
      />
      <mesh
        geometry={nodes.Mesh085.geometry}
        material={materials.Furniture_white}
      />
      <mesh geometry={nodes.Mesh085_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.polySurface4770.geometry}
        material={materials.Steel}
      />
      <mesh
        geometry={nodes.Mesh050.geometry}
        material={materials.Default_Material}
      />
      <mesh geometry={nodes.Mesh050_1.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.center_top.geometry}
        material={materials.Center_top}
      />
      <mesh
        geometry={nodes.polySurface3753.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4184.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh geometry={nodes.Mesh053.geometry} material={materials.Glass_blue} />
      <mesh geometry={nodes.Mesh053_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.door_outer_part_low.geometry}
        material={materials.door_material}
      />
      <mesh geometry={nodes.Mesh109.geometry} material={materials.Glass_blue} />
      <mesh
        geometry={nodes.Mesh109_1.geometry}
        material={materials.door_material}
      />
      <mesh
        geometry={nodes.polySurface4719.geometry}
        material={materials.Steel}
      />
      <mesh
        geometry={nodes.polySurface3767.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.polySurface4726.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh104.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh104_1.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh104_2.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh
        geometry={nodes.Mesh104_3.geometry}
        material={materials.Light_Fire}
      />
      <mesh
        geometry={nodes.Mesh104_4.geometry}
        material={materials.Light_Orange}
      />
      <mesh geometry={nodes.Mesh104_5.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh104_6.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh104_7.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh104_8.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh104_9.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh104_10.geometry}
        material={materials.Polished_metal}
      />
      <mesh
        geometry={nodes.Mesh104_11.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh104_12.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh104_13.geometry}
        material={materials.Glass_normal}
      />
      <mesh
        geometry={nodes.Mesh104_14.geometry}
        material={materials.Furniture_Orange}
      />
      <mesh
        geometry={nodes.polySurface4222.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.polySurface4225.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.polySurface4244.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.polySurface4249.geometry}
        material={materials.Aqua_tiles}
      />
      <mesh
        geometry={nodes.polySurface4250.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.polySurface4273.geometry}
        material={materials.Rosewood}
      />
      <mesh
        geometry={nodes.polySurface4277.geometry}
        material={materials.Orange_basic}
      />
      <mesh
        geometry={nodes.polySurface4279.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.polySurface4280.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.polySurface4470.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.head_exterior.geometry}
        material={materials.Steel_head}
      />
      <mesh
        geometry={nodes.polySurface4763.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4764.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4765.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4766.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4767.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.polySurface4769.geometry}
        material={materials.Steel}
      />
      <mesh geometry={nodes.Mesh046.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh046_1.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.polySurface4756.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh060.geometry}
        material={materials.Painted_wood}
      />
      <mesh geometry={nodes.Mesh060_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh060_2.geometry} material={materials.Wood} />
      <mesh
        geometry={nodes.Mesh060_3.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh060_4.geometry} material={materials.Rosewood} />
      <mesh
        geometry={nodes.polySurface4755.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.polySurface3463.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh034.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh034_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh034_2.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh geometry={nodes.Mesh034_3.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh034_4.geometry}
        material={materials.Polished_metal}
      />
      <mesh
        geometry={nodes.Mesh034_5.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh034_6.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.Mesh034_7.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh034_8.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh048.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh048_1.geometry} material={materials.Gold} />
      <mesh
        geometry={nodes.Mesh048_2.geometry}
        material={materials.Orange_basic}
      />
      <mesh
        geometry={nodes.Mesh048_3.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh048_4.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh048_5.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh048_6.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.Mesh065.geometry} material={materials.Light_Fire} />
      <mesh geometry={nodes.Mesh065_1.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh065_2.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh065_3.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh
        geometry={nodes.Mesh065_4.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh065_5.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh031.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh031_1.geometry} material={materials.Carpet} />
      <mesh geometry={nodes.Mesh024.geometry} material={materials.Light_Blue} />
      <mesh geometry={nodes.Mesh024_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Mesh064.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh064_1.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh023.geometry} material={materials.Gold} />
      <mesh
        geometry={nodes.Mesh023_1.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh023_2.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh072.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh072_1.geometry}
        material={materials.Fabric_Dark}
      />
      <mesh
        geometry={nodes.Mesh072_2.geometry}
        material={materials.Furniture_Orange}
      />
      <mesh geometry={nodes.Mesh072_3.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh072_4.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh072_5.geometry}
        material={materials.Furniture_white}
      />
      <mesh geometry={nodes.Mesh072_6.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh072_7.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.Mesh069.geometry} material={materials.Light_Blue} />
      <mesh geometry={nodes.Mesh069_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh069_2.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh069_3.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh033.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh033_1.geometry} material={materials.Gold} />
      <mesh
        geometry={nodes.Mesh062.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh062_1.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh062_2.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh geometry={nodes.Mesh062_3.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh062_4.geometry} material={materials.Rosewood} />
      <mesh geometry={nodes.Mesh062_5.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh062_6.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.Mesh062_7.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Mesh062_8.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh062_9.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh
        geometry={nodes.Mesh062_10.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh062_11.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh062_12.geometry}
        material={materials.Light_Fire}
      />
      <mesh
        geometry={nodes.Mesh056.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.Mesh056_1.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh056_2.geometry} material={materials.Screen} />
      <mesh
        geometry={nodes.Mesh056_3.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh056_4.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh056_5.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh056_6.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh056_7.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh056_8.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh056_9.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh106.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh106_1.geometry} material={materials.Rosewood} />
      <mesh
        geometry={nodes.Mesh106_2.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh106_3.geometry}
        material={materials.Wipe_marks_metal}
      />
      {/* <mesh
        geometry={nodes.Mesh036.geometry}
        material={materials.Glass_normal}
        ref={door1Ref}
      /> */}
      {/* <mesh geometry={nodes.Mesh036_1.geometry} material={materials.Wood} /> */}
      <mesh
        geometry={nodes.Mesh035.geometry}
        material={materials.Polished_metal}
      />
      <mesh
        geometry={nodes.Mesh035_1.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh035_2.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh035_3.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh035_4.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh035_5.geometry}
        material={materials.Light_Fire}
      />
      <mesh geometry={nodes.Mesh035_6.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh035_7.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh035_8.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh059.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh059_1.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh059_2.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh059_3.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh059_4.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh
        geometry={nodes.Mesh059_5.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh057.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh057_1.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh057_2.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh057_3.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh057_4.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.Mesh057_5.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh057_6.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh057_7.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh057_8.geometry}
        material={materials.Light_Orange}
      />
      <mesh geometry={nodes.Mesh084.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh084_1.geometry}
        material={materials.Orange_paint_metal}
      />
      <mesh geometry={nodes.Mesh058.geometry} material={materials.Light_Blue} />
      <mesh
        geometry={nodes.Mesh058_1.geometry}
        material={materials.Painted_wood}
      />
      <mesh
        geometry={nodes.Mesh058_2.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh058_3.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh058_4.geometry} material={materials.Light} />
      <mesh geometry={nodes.Mesh058_5.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh058_6.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Mesh058_7.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Mesh058_8.geometry} material={materials.Rosewood} />
      <mesh
        geometry={nodes.Mesh058_9.geometry}
        material={materials.Orange_basic}
      />
      <mesh
        geometry={nodes.Mesh058_10.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh058_11.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh058_12.geometry} material={materials.Wood} />
      <mesh
        geometry={nodes.Mesh058_13.geometry}
        material={materials.Polished_metal}
      />
      <mesh
        geometry={nodes.Mesh058_14.geometry}
        material={materials.Glass_normal}
      />
      <mesh
        geometry={nodes.Mesh058_15.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh058_16.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh071.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh071_1.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh geometry={nodes.Mesh071_2.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh026.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.Mesh026_1.geometry}
        material={materials.White_Mat}
      />
      <mesh geometry={nodes.Mesh026_2.geometry} material={materials.Screen} />
      <mesh
        geometry={nodes.Mesh026_3.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh037.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.Mesh037_1.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.Mesh037_2.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Mesh054.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh054_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh054_2.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh054_3.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Mesh054_4.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh054_5.geometry}
        material={materials.Glass_normal}
      />
      <mesh
        geometry={nodes.Mesh054_6.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh098.geometry} material={materials.White_Mat} />
      <mesh geometry={nodes.Mesh098_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh099.geometry} material={materials.Rosewood} />
      <mesh geometry={nodes.Mesh099_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh100.geometry} material={materials.White_Mat} />
      <mesh geometry={nodes.Mesh100_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh101.geometry} material={materials.White_Mat} />
      <mesh geometry={nodes.Mesh101_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh102.geometry} material={materials.Rosewood} />
      <mesh geometry={nodes.Mesh102_1.geometry} material={materials.Soil} />
      <mesh geometry={nodes.Mesh055.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh055_1.geometry}
        material={materials.Orange_basic}
      />
      <mesh geometry={nodes.Mesh030.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh030_1.geometry} material={materials.Screen} />
      <mesh
        geometry={nodes.Mesh030_2.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh030_3.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh geometry={nodes.Mesh091.geometry} material={materials.Glass_blue} />
      <mesh geometry={nodes.Mesh091_1.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh090.geometry} material={materials.White_Mat} />
      <mesh
        geometry={nodes.Mesh090_1.geometry}
        material={materials.Light_Orange}
      />
      <mesh geometry={nodes.Mesh089.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh089_1.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh093.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh093_1.geometry} material={materials.Rosewood} />
      <mesh
        geometry={nodes.Mesh093_2.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh094.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh094_1.geometry}
        material={materials.Aqua_tiles}
      />
      <mesh geometry={nodes.Mesh094_2.geometry} material={materials.Carpet} />
      <mesh geometry={nodes.Mesh003.geometry} material={materials.Steel} />
      <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh003_2.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh003_3.geometry}
        material={materials.Light_Orange}
      />
      <mesh geometry={nodes.Mesh014.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Mesh014_1.geometry} material={materials.Soil} />
      <mesh
        geometry={nodes.Mesh068.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh geometry={nodes.Mesh068_1.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh068_2.geometry}
        material={materials.Light_Fire}
      />
      <mesh geometry={nodes.Mesh068_3.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh068_4.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh083.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh083_1.geometry}
        material={materials.White_Mat}
      />
      <mesh
        geometry={nodes.Mesh083_2.geometry}
        material={materials.Light_Blue}
      />
      <mesh
        geometry={nodes.Mesh083_3.geometry}
        material={materials.Glass_blue}
      />
      <mesh geometry={nodes.Mesh083_4.geometry} material={materials.Wood} />
      <mesh
        geometry={nodes.Mesh083_5.geometry}
        material={materials.Aqua_tiles}
      />
      <mesh
        geometry={nodes.Mesh083_6.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh083_7.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh083_8.geometry}
        material={materials.Polished_metal}
      />
      <mesh geometry={nodes.Mesh083_9.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh083_10.geometry}
        material={materials.Light_Fire}
      />
      <mesh geometry={nodes.Mesh083_11.geometry} material={materials.Chrome} />
      <mesh geometry={nodes.Mesh083_12.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Mesh083_13.geometry} material={materials.Carpet} />
      <mesh geometry={nodes.Mesh087.geometry} material={materials.Rosewood} />
      <mesh
        geometry={nodes.Mesh087_1.geometry}
        material={materials.Light_Orange}
      />
      <mesh
        geometry={nodes.Mesh092.geometry}
        material={materials.Glass_normal}
      />
      <mesh geometry={nodes.Mesh092_1.geometry} material={materials.Steel} />
      <mesh
        geometry={nodes.Mesh092_2.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh092_3.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh092_4.geometry}
        material={materials.Wipe_marks_metal}
      />
      <mesh
        geometry={nodes.Mesh005.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh005_1.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh005_2.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh005_3.geometry}
        material={materials.Light_Blue}
      />
      <mesh geometry={nodes.Mesh005_4.geometry} material={materials.Light} />
      <mesh
        geometry={nodes.Mesh063.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh063_1.geometry}
        material={materials.Painted_wood}
      />
      <mesh geometry={nodes.Mesh063_2.geometry} material={materials.Chrome} />
      <mesh
        geometry={nodes.Mesh063_3.geometry}
        material={materials.Glass_blue}
      />
      <mesh
        geometry={nodes.Mesh063_4.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh028.geometry}
        material={materials.Furniture_white}
      />
      <mesh
        geometry={nodes.Mesh028_1.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh108.geometry}
        material={materials.Painted_Metal_White}
      />
      <mesh
        geometry={nodes.Mesh108_1.geometry}
        material={materials.Brushed_Metal}
      />
      <mesh
        geometry={nodes.Mesh108_2.geometry}
        material={materials.Light_Blue}
      />
    </group>
  );
}

useGLTF.preload("./models/spaceship/model.glb");
