/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/spaceship/Stethoscope.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import { useRef, useState } from "react";
import { useProductStore } from "../store/useProductsStore";

export function Stethoscope(props) {
  const { nodes, materials } = useGLTF("./models/spaceship/Stethoscope.glb");
  const ref = useRef();
  const [hovered, setHover] = useState(null);
  const setActiveProduct = useProductStore((s) => s.setActiveProduct);
  const setProductHovered = useProductStore((s) => s.setProductHovered);

  const productInfo = {
    title: "Stethoscope",
    description:
      "The Stethoscope is a high-quality medical instrument used by healthcare professionals to listen to heart, lung, and other body sounds. Lightweight and comfortable, it delivers clear acoustics for accurate diagnosis and is an essential tool in clinics, hospitals, and medical practice.",
    priceWas: "$200",
    priceNow: "$199",
    category: "Medical Equipments",
    image: "./images/stethoscope.jpg",
  };

  return (
    <Select enabled={hovered}>
      <group
        {...props}
        ref={ref}
        onPointerOver={() => {
          setHover(true);
          setActiveProduct(productInfo);
          setProductHovered(true);
        }}
        onPointerOut={() => {
          setHover(false);
          setProductHovered(false);
        }}
      >
        <mesh
          geometry={nodes.Stethoscope.geometry}
          material={materials["lambert1.001"]}
          position={[-10.701, -3.708, -3.724]}
          scale={0.5}
        />
      </group>
    </Select>
  );
}

useGLTF.preload("./models/spaceship/Stethoscope.glb");
